In [5]:
import pandas as pd
from sklearn import preprocessing
import numpy as np
from collections import defaultdict
import os
import pickle
import scipy.stats as st

from itertools import combinations
from scipy.stats import chi2

from code.algorithm_alpha import algorithm_alpha
from code.algorithm_t import algorithm_t
from scipy.special import factorial

In [6]:
from code.DataGeneration_class import DataGenerationBernoulli
DGB = DataGenerationBernoulli(ran_var=True, ran_int=True, n_fix=1, sim=True)

DGB.set_parameters()

[[ 1.92561  2.81464 -1.90003]
 [ 1.86938  2.36588 -1.56576]
 [ 1.01333  1.84753 -2.31159]
 [ 1.09497  2.12593 -2.2119 ]
 [ 0.81926  2.41245 -2.59227]
 [ 1.16298  2.32562 -2.79627]
 [ 0.58591  1.8137  -2.70352]
 [-4.52541 -0.073   -2.36853]
 [-4.24861  0.82347 -2.25446]
 [-4.36465  0.44519 -2.27948]]


In [7]:
fix = DGB.fix
lengths = DGB.lengths
y = DGB.y
N = DGB.N
t = DGB.t


In [8]:
N

10

In [9]:
lengths

array([84, 73, 73, 71, 80, 93, 81, 93, 84, 79])

In [10]:
for i in range(3):
    print(i)

0
1
2


In [13]:
len(t[0])

84

In [14]:
fix[0][0]

array([ 0.93492,  2.01531, -1.50976,  0.61795,  0.78252, -0.4768 ,
       -0.53232,  0.32738,  0.22497,  0.88906,  0.59267,  0.73034,
        0.93334, -1.97854, -0.01198, -0.65894,  1.48221, -0.02375,
       -0.02665, -2.37199,  2.0223 ,  0.4396 , -0.51708,  1.49071,
       -0.5153 ,  0.43371, -0.05074,  1.08384,  0.92417, -0.81018,
        1.06442,  1.34637, -0.27427, -0.253  , -0.17055,  0.94393,
       -0.6319 , -0.03891, -2.97939, -0.18683,  1.19129, -1.2673 ,
       -0.08652,  0.98131,  2.24298,  1.35622, -1.7308 ,  0.45903,
        0.62346, -1.83502, -0.76479,  0.42642,  0.33744,  0.1062 ,
       -0.43945, -0.27829, -0.02508, -0.46702, -0.99791, -1.11121,
       -0.04176, -0.98453,  1.78834, -0.8819 , -1.66813,  1.82999,
       -1.17652,  0.07982,  0.29727,  1.347  ,  0.3577 ,  0.89843,
        0.77587, -0.76621, -0.23841,  0.01042,  0.7197 , -0.91876,
        1.27658,  1.46353, -0.73822, -0.08144, -0.82663, -1.24842])

In [15]:
sim = False

ran_var = True
ran_int = True
n_fix = 1
tol = 0.05  # set as 0.01, 0.05 or 0.10 if algorithm_alpha is used; 
            # otherwise use algorithm_t and tune the tolerance tol
model = 'B' # 'B' for Bernoulli and 'P' for Poisson

# t = df.groupby('CNT')['VARIABLE_NAME'].apply(np.array).values.tolist()

knots, par, W, hess_ran, hess_fix, modeleval = algorithm_alpha(ran_var, ran_int, n_fix, sim, tol, model, fix, lengths, y, N, t)

[[ 1.92561  2.81464 -1.90003]
 [ 1.86938  2.36588 -1.56576]
 [ 1.01333  1.84753 -2.31159]
 [ 1.09497  2.12593 -2.2119 ]
 [ 0.81926  2.41245 -2.59227]
 [ 1.16298  2.32562 -2.79627]
 [ 0.58591  1.8137  -2.70352]
 [-4.52541 -0.073   -2.36853]
 [-4.24861  0.82347 -2.25446]
 [-4.36465  0.44519 -2.27948]]
0.005416817395804987
0.005717963250613257
0.005722033066639748
0.005724069171746775
0.011397719630593753
0.013285499512072873
0.013304474887738796
0.013571764642993173
0.01589819024074539
0.06900551398639916
0.013609290994688692
0.013875943239530987
0.013878505500971612
0.013879767833619206
0.02583171075381282
0.03129863091795215
0.031335303244306126
0.031584696631805124
0.033800764758158956
0.11621013522675781
0.015489551412831442
0.01573151232907984
0.015733537138181816
0.015734599839076616
0.030430979577880636
0.037798994003364964
0.03784385031692985
0.038082779455652534
0.04030523520358222
0.1309393357112639
0.016324107049010134
0.016554400973043257
0.01655619500430254
0.016557162779406